version: 0.2

phases:
  pre_build:
    commands:
      - echo Running Push to JFrog...
      - docker login -u="${JFROG_USERNAME}" -p="${JFROG_PASS}" $JFROG_HOST
  build:
    commands:
      - echo Building the Docker image... >> $IMAGE_REPO_NAME:$IMAGE_TAG        
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $JFROG_HOST/$IMAGE_REPO_NAME/$IMAGE_REPO_NAME:$IMAGE_TAG      

  post_build:
    commands:
      - echo Pushing the Docker image... $JFROG_HOST/$IMAGE_REPO_NAME/$IMAGE_REPO_NAME:$IMAGE_TAG
      - docker push $JFROG_HOST/$IMAGE_REPO_NAME/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo Push to JFrog completed on `date`
